name: CI

on:
  push:
    branches:
      - master

jobs:
  build_worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the docker image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'financial-worker-alexa' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push worker -a $APP_NAME
        heroku container:release worker -a $APP_NAME